name = "Gen"
uuid = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
authors = ["Marco Cusumano-Towner <imarcoam@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
